# Documentation: https://rmk.rs/docs/configuration.html
[keyboard]
name = "RMK MOKETA"
product_name = "MOKETA"
vendor_id = 0x0000
product_id = 0xFEED
manufacturer = "inpudiy"
chip = "nrf52840"

[matrix]
# Row and col pins are mandatory
row_pins = ["PIN_2", "PIN_21", "PIN_3", "PIN_20", "PIN_4", "PIN_19", "PIN_10"]
col_pins = ["PIN_5", "PIN_6", "PIN_7", "PIN_15", "PIN_14"]

# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

[layout]
rows = 4
cols = 12
layers = 4
keymap = [
    [    
        ["[",               "Q",               "W",               "E",               "R",               "T",                                   "Y",               "U",               "I",               "O",               "P",               "]"],
        ["Grave",           "A",  "MT(S,LAlt,HRM)", "MT(D,LCtrl,HRM)",  "MT(F,LGui,HRM)",               "G",                                   "H",  "MT(F,RGui,HRM)", "MT(D,RCtrl,HRM)",  "MT(S,RAlt,HRM)",       "Semicolon",           "Quote"],
        ["Backslash",       "Z",               "X",               "C",               "V",               "B",                                   "N",               "M",           "Comma",             "Dot",           "Slash",               "]"],
        [                                                                    "LT(2,Tab)", "MT(Space,LShift)", "LT(1,Enter)", "LT(1,Escape)",   "MT(Backspace,RShift)","LT(2,Delete)"]
    ],
    [
        ["_", "TT(1)", "TG(2)"],
        ["_", "_", "_"],
        ["_", "_", "_"],
        ["_", "_", "_"]
    ],
]
